#!/usr/bin/env python3
"""memory_tools.py — query, index, and guard the file-based memory system.

Low-tech, stdlib-only. Complements scripts/archive_memory.py. Subcommands:

  check         verify the close-out ritual is done (CURRENT STATE dated today,
                a session entry for today, registries well-formed). Exit 1 on fail.
  index         regenerate memory-index.md (a TOC of every session, hot + archived).
  search QUERY  case-insensitive search across memory + registries + docs.
  decisions     list decisions from DECISIONS.md   (--client X to filter).
  open          list open questions from OPEN-QUESTIONS.md (--client X, --stale N).
  reconcile     flag CURRENT STATE staleness: dead file refs, old date, aged questions.
  install-hooks install a git pre-push hook that runs `check` (warn-only by default).

Conventions this tool expects (see docs/memory-system.md):
  - Session headers:  ## Session NNN (YYYY-MM-DD, Environment): title
  - DECISIONS.md row: - [D-NNN] YYYY-MM-DD | Client | text (Sxxx)
  - OPEN row (open):  - [ ] [Q-NNN] YYYY-MM-DD | Client | text (opened Sxxx)
  - OPEN row (done):  - [x] [Q-NNN] ... RESOLVED Sxxx: ...
"""
import argparse, datetime, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEM = os.path.join(ROOT, 'memory.md')
ARC = os.path.join(ROOT, 'memory-archive.md')
DEC = os.path.join(ROOT, 'DECISIONS.md')
OPN = os.path.join(ROOT, 'OPEN-QUESTIONS.md')
IDX = os.path.join(ROOT, 'memory-index.md')

SESSION_RE = re.compile(r'^##\s+Session\s+(\d+)\s+\(([\d-]+),\s*([^)]*?)\):\s*(.*)$', re.M)
DEC_RE = re.compile(r'^-\s+\[D-(\d+)\]\s+([\d-]+)\s+\|\s+([^|]+?)\s+\|\s+(.*)$')
OPN_RE = re.compile(r'^-\s+\[( |x)\]\s+\[Q-(\d+)\]\s+([\d-]+)\s+\|\s+([^|]+?)\s+\|\s+(.*)$')
OPENED_RE = re.compile(r'opened\s+S(\d+)', re.I)


def read(path):
    try:
        with open(path, encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return ''


def today():
    return datetime.date.today().isoformat()


def current_state_block():
    t = read(MEM)
    m = re.search(r'##\s+CURRENT STATE.*?\n(.*?)\n---', t, re.S)
    return m.group(1) if m else ''


def last_updated():
    m = re.search(r'Last updated:\s*([\d-]+)', current_state_block())
    return m.group(1) if m else None


def all_sessions():
    """(num, date, env, title) newest-first across hot + archive."""
    out = []
    for path in (MEM, ARC):
        for m in SESSION_RE.finditer(read(path)):
            out.append((int(m.group(1)), m.group(2), m.group(3).strip(), m.group(4).strip()))
    out.sort(key=lambda r: r[0], reverse=True)
    return out


def latest_session_num():
    s = all_sessions()
    return s[0][0] if s else 0


# ---------------- commands ----------------

def cmd_check(args):
    fails, warns = [], []
    lu = last_updated()
    if lu != today():
        fails.append(f'CURRENT STATE "Last updated" is {lu}, expected today ({today()}).')
    if not any(d == today() for _, d, _, _ in all_sessions()):
        fails.append(f'No session entry dated today ({today()}) in memory.md.')
    # registries must parse
    for path, rx, label in ((DEC, DEC_RE, 'DECISIONS.md'), (OPN, OPN_RE, 'OPEN-QUESTIONS.md')):
        for i, ln in enumerate(read(path).splitlines(), 1):
            s = ln.rstrip()
            if s.startswith('- [') and not rx.match(s):
                warns.append(f'{label}:{i} malformed row: {s[:70]}')
    # archive reminder
    if os.path.exists(MEM) and os.path.getsize(MEM) > 90_000:
        warns.append('memory.md > 90KB — run scripts/archive_memory.py.')
    for w in warns:
        print(f'  warn: {w}')
    if fails:
        for fmsg in fails:
            print(f'  FAIL: {fmsg}')
        print('close-out check: FAILED')
        return 1
    print('close-out check: OK' + (f' ({len(warns)} warning(s))' if warns else ''))
    return 0


def cmd_index(args):
    rows = all_sessions()
    lines = ['# Memory index (sessions)', '',
             '> AUTO-GENERATED by `scripts/memory_tools.py index` — do not edit by hand.',
             f'> {len(rows)} sessions. Regenerate at close-out.', '',
             '| # | Date | Env | Title |', '|---|------|-----|-------|']
    for num, date, env, title in rows:
        lines.append(f'| {num} | {date} | {env} | {title.replace("|", "/")} |')
    with open(IDX, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {os.path.relpath(IDX, ROOT)} ({len(rows)} sessions)')
    return 0


def cmd_search(args):
    q = ' '.join(args.query).lower()
    if not q:
        print('usage: search <query>'); return 1
    targets = [MEM, ARC, DEC, OPN]
    targets += [os.path.join(ROOT, 'docs', f) for f in sorted(os.listdir(os.path.join(ROOT, 'docs')))
                if f.endswith('.md')] if os.path.isdir(os.path.join(ROOT, 'docs')) else []
    hits = 0
    for path in targets:
        for i, ln in enumerate(read(path).splitlines(), 1):
            if q in ln.lower():
                print(f'{os.path.relpath(path, ROOT)}:{i}: {ln.strip()[:160]}')
                hits += 1
    print(f'--- {hits} match(es) for "{q}"')
    return 0


def _rows(path, rx):
    for ln in read(path).splitlines():
        m = rx.match(ln.rstrip())
        if m:
            yield m


def cmd_decisions(args):
    n = 0
    for m in _rows(DEC, DEC_RE):
        did, date, client, text = m.group(1), m.group(2), m.group(3).strip(), m.group(4)
        if args.client and args.client.lower() not in client.lower():
            continue
        print(f'D-{did}  {date}  [{client}]  {text}')
        n += 1
    print(f'--- {n} decision(s)' + (f' for {args.client}' if args.client else ''))
    return 0


def cmd_open(args):
    latest = latest_session_num()
    n = 0
    for m in _rows(OPN, OPN_RE):
        done, qid, date, client, text = m.group(1) == 'x', m.group(2), m.group(3), m.group(4).strip(), m.group(5)
        if done:
            continue
        if args.client and args.client.lower() not in client.lower():
            continue
        age = ''
        om = OPENED_RE.search(text)
        if om and latest:
            gap = latest - int(om.group(1))
            if args.stale and gap >= args.stale:
                age = f'  ⚠ open {gap} sessions'
        print(f'Q-{qid}  {date}  [{client}]  {text}{age}')
        n += 1
    print(f'--- {n} open question(s)' + (f' for {args.client}' if args.client else ''))
    return 0


def cmd_reconcile(args):
    print('CURRENT STATE reconcile:')
    block = current_state_block()
    lu = last_updated()
    if lu != today():
        print(f'  - date: "Last updated" is {lu} (today is {today()}) — refresh it.')
    # dead file references: only fully-qualified paths from a known top-level dir
    # (basenames and partial paths are ambiguous references, not checkable — skip them)
    refs = set(re.findall(r'(?<![\w`/])((?:clients|scripts|docs|compositions|brand)/[\w./-]+)', block))
    dead = []
    for r in sorted(refs):
        p = r.rstrip('.,);')
        if '*' in p or not os.path.exists(os.path.join(ROOT, p)):
            dead.append(p)
    if dead:
        print('  - dead path refs (moved/renamed/deleted?):')
        for d in dead:
            print(f'      {d}')
    else:
        print('  - file refs: all resolve ✓')
    # aged open questions
    latest = latest_session_num()
    aged = []
    for m in _rows(OPN, OPN_RE):
        if m.group(1) == 'x':
            continue
        om = OPENED_RE.search(m.group(5))
        if om and latest and latest - int(om.group(1)) >= 5:
            aged.append(f'Q-{m.group(2)} (open {latest - int(om.group(1))} sessions): {m.group(5)[:70]}')
    if aged:
        print('  - aged open questions (>=5 sessions) — resolve or re-justify:')
        for a in aged:
            print(f'      {a}')
    print('  - manual: confirm each CURRENT STATE bullet is still TRUE and the "Next" line is right.')
    return 0


HOOK = """#!/bin/sh
# Auto-installed by scripts/memory_tools.py install-hooks.
# Warns (does not block) if the close-out ritual is incomplete before a push.
# Set MEMORY_ENFORCE=1 to make it block.
out=$(python3 "%s" check 2>&1)
echo "$out"
echo "$out" | grep -q "FAILED" || exit 0
if [ "$MEMORY_ENFORCE" = "1" ]; then
  echo "memory close-out incomplete (MEMORY_ENFORCE=1) — push blocked. Fix or: git push --no-verify" >&2
  exit 1
fi
echo "(reminder only — push allowed. Set MEMORY_ENFORCE=1 to block.)" >&2
exit 0
""".strip()


def cmd_install_hooks(args):
    hooks_dir = os.path.join(ROOT, '.git', 'hooks')
    if not os.path.isdir(hooks_dir):
        print('no .git/hooks directory — is this a git repo?'); return 1
    dst = os.path.join(hooks_dir, 'pre-push')
    with open(dst, 'w') as f:
        f.write(HOOK % os.path.join(ROOT, 'scripts', 'memory_tools.py') + '\n')
    os.chmod(dst, 0o755)
    print(f'installed {os.path.relpath(dst, ROOT)} (warn-only; MEMORY_ENFORCE=1 to block).')
    return 0


def main():
    ap = argparse.ArgumentParser(description='Query and guard the file-based memory system.')
    sub = ap.add_subparsers(dest='cmd', required=True)
    sub.add_parser('check')
    sub.add_parser('index')
    sp = sub.add_parser('search'); sp.add_argument('query', nargs='+')
    sp = sub.add_parser('decisions'); sp.add_argument('--client', default='')
    sp = sub.add_parser('open'); sp.add_argument('--client', default=''); sp.add_argument('--stale', type=int, default=5)
    sub.add_parser('reconcile')
    sub.add_parser('install-hooks')
    args = ap.parse_args()
    fn = {'check': cmd_check, 'index': cmd_index, 'search': cmd_search, 'decisions': cmd_decisions,
          'open': cmd_open, 'reconcile': cmd_reconcile, 'install-hooks': cmd_install_hooks}[args.cmd]
    sys.exit(fn(args))


if __name__ == '__main__':
    main()
